name: test
on:
  pull_request

jobs:
  test-cowsay:
    name: Run Tests
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install nim
        uses: jiro4989/setup-nim-action@v1.3.4
        with:
          nim-version: 1.4.8

      - name: Install cowsay
        run: |
          sudo apt-get update -y
          sudo apt-get install -y cowsay
          echo "/usr/games" >> $GITHUB_PATH

      - name: Update Nimble packages.
        run: nimble refresh

      - name: Run tests
        run: nimble test
