name: test
on:
  pull_request

jobs:
  test-cowsay:
    name: Run Tests
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install nim
        uses: jiro4989/setup-nim-action@v1.4.6

      # Install from repo because the cowsay available in apt
      # doesn't have all the cows.
      - name: Fetch cowsay
        run: git clone https://github.com/schacon/cowsay.git /tmp/cowsay

      - name: Install cowsay
        working-directory: /tmp/cowsay
        run: sudo ./install.sh /usr/local

      - name: Check which cowthink
        run: which cowthink

      - name: Think something
        run: cowthink whatever

      - name: Update Nimble packages.
        run: nimble refresh

      - name: Run tests
        run: nimble test
